language: python

services:
	- postgresql

install:
	- pip install -r requirements.txt
	- pip install coverage
	- pip install codecov

before_script:
	- psql -c 'CREATE DATABASE chargetracker;' -U postgres

